FROM nginx:1.21.0-alpine

LABEL maintainer Richard Willis <willis.rh@gmail.com>
LABEL org.opencontainers.image.source https://github.com/badsyntax/docker
LABEL org.label-schema.name="base-nginx"
LABEL org.label-schema.description="Base nginx"
LABEL org.label-schema.vcs-url="https://github.com/badsyntax/docker"
LABEL org.label-schema.usage="README.md"
LABEL org.label-schema.vendor="badsyntax"

COPY ./nginx /etc/nginx
